// Đường dẫn: src/constants/dashboard-text.ts

export const DASHBOARD_TEXT = {
    HEADER: {
      TITLE: "Quản lý dự án",
      SUBTITLE: "",
      BTN_ADD_NEW: "Thêm Dự án mới",
    },
    METRICS: {
      TOTAL_PROJECTS: "Tổng Dự Án",
      CHUA_BAN_HANH: "Chưa ban hành",
      CHUA_KIEM_KE: "Chưa kiểm kê",
      DANG_GIAI_QUYET: "Đang giải quyết",
    },
    PROJECT_CARD: {
      EMPTY_STATE: "Không có dự án nào khớp bộ lọc.",
      CATEGORY: "Phân loại",
      NO_CATEGORY: "Chưa cập nhật",
      COMPLETED: "Hoàn thành",
      OVERDUE_BADGE: "Quá hạn",
      DEADLINE_PREFIX: "Hạn:",
      NO_DEADLINE: "Chưa đặt",
      PROGRESS_TITLE: "Tiến độ Phê duyệt",
      UNIT_LOT: "lô",
    },
    MODAL_TABS: {
      PROGRESS: "Tiến độ GPMB",
      DETAILS: "Thông tin chung",
      HISTORY: "Lịch sử",
    },
    FORM: {
      TITLE_CREATE: "Khởi tạo Dự án mới",
      TITLE_UPDATE: "Hồ sơ Dự án",
      BTN_EDIT: "Chỉnh sửa thông tin",
      BTN_SAVE_CHANGES: "Lưu thay đổi",
      BTN_SAVE_PROGRESS: "Lưu Tiến Độ & Hạn chót",
      BTN_SAVE_NEW: "Lưu Dự Án Mới",
      BTN_CANCEL: "Hủy",
      LOADING: "Đang lưu...",
      CREATING: "Đang tạo...",
    },
    FIELDS: {
      NAME: "Tên dự án *",
      CODE: "Mã dự án",
      DEADLINE: "Hạn chót hoàn thành",
      DEADLINE_DATETIME: "Hạn chót (Giờ & Ngày)",
      TIEN_DO_GROUP: "Nhóm tiến độ dự án",
      CHI_TIET_STATUS: "Tình trạng (Chi tiết)",
      DON_VI_DO_DAC: "Đơn vị đo đạc",
      CAN_BO: "Cán bộ phụ trách GPMB",
      MO: "Tình trạng Mộ",
      GHI_CHU: "Ghi chú",
      TOTAL_SCALE: "Quy mô Tổng (Tự động)",
      CHUA_BAN_HANH: "Chưa ban hành",
      CHUA_KIEM_KE: "Chưa kiểm kê",
      GROUP_DANG_GIAI_QUYET: "Nhóm Đang giải quyết",
      XAC_NHAN: "Xác nhận",
      DU_THAO: "Dự thảo",
      THAM_DINH: "Thẩm định",
      PHE_DUYET: "Đã Phê duyệt",
    },
    PLACEHOLDERS: {
      NAME: "Nhập tên dự án...",
      CODE: "VD: DA-001",
      DON_VI: "Tên đơn vị...",
      CAN_BO: "Họ tên cán bộ...",
      MO: "Số lượng mộ, hiện trạng...",
      GHI_CHU: "Các thông tin bổ sung...",
      EMPTY_FIELD: "---",
      NO_NOTES: "Không có ghi chú",
      NO_MO: "Không có ghi nhận",
      NOT_SET_DEADLINE: "--- Chưa thiết lập ---",
    },
    HISTORY: {
      EMPTY: "Chưa có lịch sử cập nhật nào.",
    },
    NOTIFICATIONS: {
      OVERDUE_TITLE: "QUÁ HẠN HOÀN THÀNH",
      OVERDUE_SUB: "Đã quá hạn tiến độ!",
      DEADLINE_LABEL: "Hạn cuối:",
      ERR_MISSING_NAME: "Vui lòng nhập tên dự án!",
      ERR_CREATE: "Lỗi tạo dự án.",
      ERR_CONNECT: "Lỗi kết nối!",
    }
  };